plugins {
    id "com.android.application"
}

android {
    namespace = "com.github.muellerma.coffee"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.github.muellerma.coffee"
        minSdk = 37
        targetSdk = 37
        versionCode = 49
        versionName = "3.1"
    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
        debug {
            applicationIdSuffix = ".debug"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        encoding = "UTF-8"
    }

    lint {
        abortOnError = true
        warningsAsErrors = true
    }
}
